[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'beikome/cosme.vim'
hook_add = '''
  colorscheme cosme
'''

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'sheerun/vim-polyglot'
